### ISSUE TITLE
Question: Change eClass string serialization

### ISSUE THREAD

**Issue by tarelli** [emfjson/emfjson-jackson#75]
What would be the recommended way to change the way the eClass string is serialised? That long string is in every object we have (and we have thousands), basically looking to have a shortened representation (something like what's after the #//). Maybe having the namespace factored out like they do in the XMIs? We have an absolute URI for the schema so that XMI can be opened regardless of their location with the dynamic editor.

![screen shot 2015-12-10 at 12 19 04](https://cloud.githubusercontent.com/assets/81127/11715274/6d8d3ed0-9f38-11e5-8955-00e65b43eb78.png)

Thanks!

**Comment by ghillairet** [comment]
In general the eClass URI should be like it's ePackage nsURI, maybe you did not register the ePackage correctly.

Otherwise you can use customs de/serializers for types like it's done here https://github.com/emfjson/emfjson-jackson/blob/master/src/test/java/org/emfjson/jackson/junit/tests/CustomSerializersTest.java#L55 and https://github.com/emfjson/emfjson-jackson/blob/master/src/test/java/org/emfjson/jackson/junit/tests/CustomDeserializersTest.java#L60

**Comment by tarelli** [comment]
It is the ePackage nsURI it's just a bit cumbersome to have it for every object. Thanks for the links, it's what I was looking for!
